### PR TITLE
make it actually work

### PR DESCRIPTION
**Pull request by ArtOfCode-**
Currently only works once on page load, if you're lucky. This makes it run every 2 seconds.

### CODE REVIEW

**Comment by tckmn** [comment]
The [original purpose of this script](http://meta.stackexchange.com/a/246765/180276) was to only run in the transcript (hence the name). It makes sense to make it work for the actual chat page as well, but do you think there's any more elegant way than just running it once every 2 seconds? (Perhaps I could make it subscribe to message deletion events on the websocket.)

**Comment by ArtOfCode-** [comment]
@KeyboardFire I actually implemented it as a keyboard shortcut originally (that's what I have running), but I moved it to using timeouts here because that's what was already in use. I can change this one to the keyboard version, if that's preferable?

**Comment by tckmn** [comment]
Sure, that works; go ahead and change it to that version (it would be great if you could rebase the two commits into one also).

**Comment by ArtOfCode-** [comment]
@KeyboardFire that's done; works on Ctrl-D.

**Pull request merged**
